### ISSUE TITLE
ota升级不了

### ISSUE THREAD

**Issue by akercn** [a2633063/zTC1#10]
APP版本0.8，固件是0.9。点击升级更新能检测到0.91点升级以后没有升级进度什么的就看到tc1灯闪几下。用APP检查结果一样还是0.9好像没有升级一样。是我操作问题还是怎样？

**Comment by babylife** [comment]
已知问题 服务器故障 请自建http服务器 升级新版本app可以输入ota地址

**Comment by akercn** [comment]
新版APP在哪里？看这里的还是0.8

**Comment by babylife** [comment]
在qq群里面

**Comment by a2633063** [comment]
新版本app有bug  所以没有release出来 放在群里只是测试临时用   后面还是会release出来的

**Comment by akercn** [comment]
OK，我就等等吧！

**Comment by godt2p4** [comment]
固件是0.6，手机APP已经是0.9，填入bin的地址无法OTA升级（试过0.7 0.8 0.9 0.10都无效）

**Comment by a2633063** [comment]
填入bin的地址需要自行建立服务器  是否建立服务器?
