### ISSUE TITLE
希望在app端添加重启功能

### ISSUE THREAD

**Issue by babylife** [a2633063/zTC1#11]
微信小程序似乎要重启TC1才可以，希望可以实现app端重启的功能

**Comment by a2633063** [comment]
tc1如果配置过mqtt服务器,再次配置mqtt服务器时,必须重启tc1才能使新的mqtt服务器设置生效, 所以是否是你之前配置过mqtt服务器,在使用微信小程序时设置成微信小程序对应的mqtt地址,重启固件才能使新设置生效表现即为重启TC1才可以

**Comment by a2633063** [comment]
后续版本增加通过通讯协议重启固件功能.

**Comment by babylife** [comment]
fixed .close
