### ISSUE TITLE
刷机失败 灯也不亮 电源也没反应啦…

### ISSUE THREAD

**Issue by darktitty** [a2633063/zTC1#15]
几次刷 没对齐 直接废了…

**Comment by a2633063** [comment]
应该不会刷废   检查接线多试几次

**Comment by darktitty** [comment]
怎么检查接线啊？ 我尝试了几次都不行 灯都不亮 一点反应没有

**Comment by akercn** [comment]
电源线进来连接的那个小板底下是有排针和下面连接的，你是不是动到这个板子了。

**Comment by darktitty** [comment]
不知道啊 当时有可能放到了一个导电的底板上也有可能…是不是没救啦？

**Comment by darktitty** [comment]
至于说两个板子松动这种情况应该不会…

**Comment by a2633063** [comment]
没有错误提示没有烧录器型号等内容 无法提供帮助  仔细阅读文档吧
理论上烧录几次不会损坏设备
