### ISSUE TITLE
请问如何自动升级固件？

### ISSUE THREAD

**Issue by zwl0499** [a2633063/zTC1#19]
如何自动升级固件？ 需要自己填网址？

**Comment by babylife** [comment]
可以自己部署一个http server进行更新

**Comment by a2633063** [comment]
因为暂时没有服务器 你可以尝试自己搭建httpserver 或是你可以邮件我 我会反馈给你最想固件的ota地址

**Comment by vincenthsing** [comment]
> 因为暂时没有服务器 你可以尝试自己搭建httpserver 或是你可以邮件我 我会反馈给你最想固件的ota地址

自己搭建服务器这块,有具体的文档吗?wiki里面没有找到类似的东西,只看到说用马云的服务器ota了,麻烦大佬不吝赐教,谢谢

**Comment by a2633063** [comment]
> > 因为暂时没有服务器 你可以尝试自己搭建httpserver 或是你可以邮件我 我会反馈给你最想固件的ota地址
> 
> 自己搭建服务器这块,有具体的文档吗?wiki里面没有找到类似的东西,只看到说用马云的服务器ota了,麻烦大佬不吝赐教,谢谢

不打算写文档 本来只是做固件而已  外网控制/mqtt服务器搭建/ota服务器搭建涉及的东西太多了 没有这个精力做这个文档和答疑   
所以如果你需要ota升级 直接发送邮件给我  我会回复ota的地址的
