### ISSUE TITLE
如何用0.9版本的APP升级固件啊，TC1现在是0.6版本

### ISSUE THREAD

**Issue by godt2p4** [a2633063/zTC1#24]
在APP里连接设备的设置里，点击当前版本（点击检查新版本），出来的是一个“请输入固件下载地址”的弹出框，不知道如何进行下去升级，多谢！

**Comment by godt2p4** [comment]
APP换成0.8版本后，按检查固件版本会提示最新的版本是0.10，但是按更新后，TC1闪烁了几下伴随一声复位声后就没任何反应了，固件也没因此更新

**Comment by a2633063** [comment]
请使用最新版本app 填写的地址请发邮件给我 回复给你

**Comment by godt2p4** [comment]
自建了一个webdev搞定了，现在已经升级到0.10.1了，多谢！期待USB四口的控制功能早日实现，加油！

**Comment by godt2p4** [comment]
期待USB四口的控制功能早日实现，加油！
