### ISSUE TITLE
修改TC1名字问题

### ISSUE THREAD

**Issue by HuaZao** [a2633063/zTC1#27]
通过UDP指令发送
publishMessage String -> {"name":"三楼房间","mac":"d0bae463c9a0"}
硬件返回数据:
{
  "name" : "zTC1_C9A0",
  "mac" : "d0bae463c9a0"
}
无法修改name,请问是插座的name是不允许修改的吗?

**Comment by a2633063** [comment]
可以修改
修改名称应该为
`{"mac" : "d0bae463c9a0","setting":{"name":"三楼房间"}}`

如果自己使用通讯协议进行配置,请仔细阅读wiki上通讯协议章节

**Comment by HuaZao** [comment]
好~谢谢,测试正常了
