### ISSUE TITLE
A1版刷完固件变砖了

### ISSUE THREAD

**Issue by zoengzihaam** [a2633063/zTC1#29]
刷上成功 指示灯就灭了 就再也不亮了 插座也都没电了

**Comment by a2633063** [comment]
请确认刷机的bin文件为all.bin  而不是ota.bin
刷机在接线正确的情况下一般不会导致变砖,直接重刷即可

**Comment by jjss520** [comment]
我也是，好像是第一次刷的时候，把,dio与jlink的swdio相连,clk与jlink的swclk相连，这两个线序，弄反了，然后还刷成功了，然后，重新上电，指示灯还闪，后面刷，一直提示连接不上，然后再是电，没什么反应，，，

**Comment by a2633063** [comment]
照理这样应该不会烧录成功.
这样接反也会损坏设备,重新烧录

**Comment by jjss520** [comment]
> 照理这样应该不会烧录成功.
> 这样接反也会损坏设备,重新烧录

现在上电，机器没任何反应，烧录，直接提示连接jlink

**Comment by a2633063** [comment]
> > 照理这样应该不会烧录成功.
> > 这样接反也会损坏设备,重新烧录
> 
> 现在上电，机器没任何反应，烧录，直接提示连接jlink

难道是把烧录器烧了???  我不确定  手上用的烧录器和你们20左右的不一样所以我不确定是否有影响
可以先确认烧录器正常

**Comment by jjss520** [comment]
> 烧录
插上烧录器，设备管理器里也有，烧录器灯也有亮
我重新换台电脑试试

**Comment by jjss520** [comment]
成功解决，感谢a2633063的固件和教程，触点有条件一定用焊的方法，前面一直手按的，折腾的不行。

**Comment by jjss520** [comment]
麻烦给个ota升级的地址，谢谢


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Zip Zhang <notifications@github.com>
发送时间: 2019年5月13日 16:10
收件人: a2633063/zTC1 <zTC1@noreply.github.com>
抄送: jjss520 <562461306@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[a2633063/zTC1] A1版刷完固件变砖了 (#29)



  
照理这样应该不会烧录成功.
 这样接反也会损坏设备,重新烧录
  
现在上电，机器没任何反应，烧录，直接提示连接jlink
  
难道是把烧录器烧了???  我不确定  手上用的烧录器和你们20左右的不一样所以我不确定是否有影响
 可以先确认烧录器正常

**Comment by a2633063** [comment]
ota地址不会在这里发, 请发邮件给我
