### ISSUE TITLE
SmartControl_Android_MQTT配对问题

### ISSUE THREAD

**Issue by zoengzihaam** [a2633063/zTC1#30]
使用a大的软件进行配对 插排一直没什么反应 app也一直是在配对 使用另一个软件连接上网络 在app中添加局域网设备也始终无反应 不知道a大能否解答这个问题

**Comment by a2633063** [comment]
请仔细阅读文档,实际测试, ssid中有特殊字符可能失败,不能为中文 不能含有空格 建议使用easylink配对试试看https://www.mxchip.com/easylink/

**Comment by a2633063** [comment]
后续可能会修改配对方式

**Comment by zoengzihaam** [comment]
已经解决了 谢谢解答
