### ISSUE TITLE
据说TC1这里不会更新断电bug了？

### ISSUE THREAD

**Issue by darktitty** [a2633063/zTC1#31]
这个bug很严重啊 这样的话 那请问大佬 我还有机会让我的TC1变回普通插座不…

**Comment by a2633063** [comment]
断电bug后期会修复,实际上已经修复了  但是因为被不良商用问题没有放出  建议等一段时间 我会想办法解决 尽量快点放出  再此之前 在意重启的话先暂时不要使用

**Comment by darktitty** [comment]
好的 敬候佳音~

**Comment by aduhappy** [comment]
等待可以不重启再上车

**Comment by jiafengwang** [comment]
请问最新的v0.10.1有修复了吗？

**Comment by aduhappy** [comment]
不知道啊，没用，

**Comment by a2633063** [comment]
已更新至0.10.3修复此问题

**Comment by darktitty** [comment]
终于等到了 谢谢大佬  可以直接在线更新吗? 还是说需要更新链接?

**Comment by a2633063** [comment]
先更新app到0.10.3 可以直接OTA

**Comment by darktitty** [comment]
升级成功了…无法控制 重新配对 等直接灭 让后也无法控制…

**Comment by a2633063** [comment]
请根据文档获取激活码并激活

**Comment by darktitty** [comment]
搞定了 谢谢大佬
