### ISSUE TITLE
会添加在线服务器吗？不在家怎么控制呢，没有自己的服务器。。。。

### ISSUE THREAD

**Issue by gutyu** [a2633063/zTC1#32]
会添加在线服务器吗？不在家怎么控制呢，没有自己的服务器。。。。

**Comment by a2633063** [comment]
个人不会提供  有人会在意个人开发的固件连接了私人的服务器   所以才设计为mqtt服务器都是手动输入的方式(实际上这种方式在配置时很不方便 但是为了那些人只能这样了)  目前在群里有群友提供一个mqtt服务器(可以用微信小程序控制) 作者禁止外传  所以需要可以进群获取使用

**Comment by min116** [comment]
请问群号多少

**Comment by a2633063** [comment]
> 请问群号多少

群号在文档中找  现在那个微信小程序已经不能用了

**Comment by gutyu** [comment]
459996006 这个是群号

在 2019-08-30 08:08:36，"Zip Zhang" <notifications@github.com> 写道：


请问群号多少

群号在文档中找 现在那个微信小程序已经不能用了

**Comment by gutyu** [comment]
459996006

在 2019-08-27 20:11:23，"min116" <notifications@github.com> 写道：


请问群号多少
