### ISSUE TITLE
按住logo开机之后，指示灯一直闪烁，不变常亮

### ISSUE THREAD

**Issue by gaoliang** [a2633063/zTC1#36]
刷机成功之后，按住logo，然后接入电源线，指示灯一直是闪烁状态，没有变成常亮

**Comment by sumeoy** [comment]
我也遇到这种情况，刷完固件后，按logo十秒后，闪烁完了就不会常亮了。

**Comment by gaoliang** [comment]
同上，搞定，开机之前先长按一会。
