### ISSUE TITLE
死活连不上，可不可以提供一个默认可以当普通插排的固件？

### ISSUE THREAD

**Issue by smart-z** [a2633063/zTC1#39]
点击配网，要么就是灯常亮毫无闪烁的变化；要么就是会闪烁个不停，然后就没有然后了。

现在一直配网不成功。

一切都是按描述做的。甚至wifi名字密码都改成很简单的都试过几次，还是不行。完全配网不成功。

能不能提供一个设置或修改的固件，默认可以当作普通插排来使用器？现在这样，插上电除了USB其他的插孔完全不能用，废了，真是太糟心了。请务必解决一下。

**Comment by a2633063** [comment]
不提供 
进入配网模式时灯是常亮 如果点配对后边为闪烁证明数据传输了  闪烁表示正在连接wifi 
如果多次尝试还是失败,可以在https://www.mxchip.com/easylink/ 下载app配对试试
另外 配网是有人给我反应容易失败,大部分是**不认真看文档**,少部分路由器固件导致

**Comment by smart-z** [comment]
> 不提供
> 进入配网模式时灯是常亮如果点配对后边为闪烁证明数据传输了闪烁表示正在连接wifi 
> 如果多次尝试还是失败,可以在https://www.mxchip.com/easylink/下载app配对试试
> 另外配网是有人给我反应容易失败,大部分是**不认真看文档** ,少部分路由器固件导致

太好了，总算有有点希望了，我折腾折腾 easylink 看看，昨天就是没有找到是那个easylink。先谢了。

**Comment by LuckyIV** [comment]
我一开始也是死活连不上，后来尝试把路由器设置里的突发传输（TX优先），智能抗干扰和智能合频关掉后可以连接，具体是哪个选项导致的问题我没有试

**Comment by ZlWcc** [comment]
我也配对不了。不同的是灯一直常亮，App一直在“正在配对，请稍后……”。文档都能背了，然而……

**Comment by ZlWcc** [comment]
> 我一开始也是死活连不上，后来尝试把路由器设置里的突发传输（TX优先），智能抗干扰和智能合频关掉后可以连接，具体是哪个选项导致的问题我没有试

路由器问题配对不上的情况，点配对LED灯会闪吗？

**Comment by a2633063** [comment]
> > 我一开始也是死活连不上，后来尝试把路由器设置里的突发传输（TX优先），智能抗干扰和智能合频关掉后可以连接，具体是哪个选项导致的问题我没有试
> 
> 路由器问题配对不上的情况，点配对LED灯会闪吗？

进入配网模式时灯是常亮 一直常亮可以在https://www.mxchip.com/easylink/ 下载app配对试试

**Comment by 925934787** [comment]
> > > 我一开始也是死活连不上，后来尝试把路由器设置里的突发传输（TX优先），智能抗干扰和智能合频关掉后可以连接，具体是哪个选项导致的问题我没有试
> > 
> > 
> > 路由器问题配对不上的情况，点配对LED灯会闪吗？
> 
> 进入配网模式时灯是常亮 一直常亮可以在https://www.mxchip.com/easylink/ 下载app配对试试

我重刷了固件，然后现在进入配对模式（断电长按logo按钮），灯闪烁两次之后，常亮，但是常亮只有3-5秒就直接灭了，手机也是一直正在连接，最后很久之后失败，请问一下是不是没刷好，还是插排损坏了？

**Comment by nsb2006** [comment]
> 我一开始也是死活连不上，后来尝试把路由器设置里的突发传输（TX优先），智能抗干扰和智能合频关掉后可以连接，具体是哪个选项导致的问题我没有试

感谢分享，我的德业除湿机在家里换了使用梅林固件的网件路由器之后始终连不上手机，研究了一番查出来德业除湿机用的无线方案是MXCHIP的，一路找到这里，关了路由器2.4G的Tx Burst选项之后成功连接。
