### ISSUE TITLE
考虑homeassistant集成定时，通过浏览器OTA吗？

### ISSUE THREAD

**Issue by ghostist** [a2633063/zTC1#4]
目的是尽量集成到一个app里（HA），减少手机上app数量
OTA可以通过浏览器的方式吗？手持苹果手机，配网还得找人帮忙

**Comment by a2633063** [comment]
已经可以通过ha来控制设备.
暂时不考虑直接通过浏览器来进行OTA,但是你可以使用MQTT直接发送数据给zTC1来实现无app的情况下ota.
详细数据见https://github.com/a2633063/zTC1/wiki/%E9%80%9A%E4%BF%A1%E5%8D%8F%E8%AE%AE
