### ISSUE TITLE
掉ip

### ISSUE THREAD

**Issue by CCZU1623** [a2633063/zTC1#46]
固件版本(必填):v1.0.0

App版本(与app控制有关时必填):v0.11.6

Android版本(与app控制有关时必填):9

是否使用服务器(必填):否

问题描述(包含复现issue方式):更新固件到1.0.0版本后出现与路由器断连的问题，ztc1从路由器设备列表消失，导致无法控制，即使重启路由器ztc1仍然连接不上路由器，初步考虑不是路由器的问题，出现该问题只能重新插拔tc1的插头才能重新连接路由热点，路由器就放在插座旁边，与信号强度无关。刷完机后我从未拔过tc1插头关过机，该问题仅在v1.0.0版本出现，之前的版本从未出现该问题，故考虑是固件的问题。

复现方法:开机几十小时后就会出现

**Comment by hwj180** [comment]
感觉不是真的未连接，而是进入省电模式，实际使用局域网UDP模式还能控制的。

**Comment by CCZU1623** [comment]
感觉并不是进入所谓的”省电模式”，手机连接路由热点后尝试用ZControl控制ztc1，然而操作是无效的，app中看不到设备当前状态，路由器设备列表里也显示ztc1离线

**Comment by hwj180** [comment]
UDP那个你勾选上试试

**Comment by CCZU1623** [comment]
是的，因为我没有用服务器，”总是通过UDP发送数据”一项一直都是勾选状态，但仍然无法控制

**Comment by hwj180** [comment]
哦，那就不知道了，我勾UDP，在局域网能控制。

**Comment by CCZU1623** [comment]
好，也感谢您提出的解决方法，后续几天若不会复现该问题我会关闭这个issue
