### ISSUE TITLE
固件没有发布power和total_time信息

### ISSUE THREAD

**Issue by everything411** [a2633063/zTC1#48]
固件版本(必填):v1.0.2

App版本(与app控制有关时必填):
v0.12.2
Android版本(与app控制有关时必填):
android9/miui 11
是否使用服务器(必填):
本地openwrt mosquito mqtt server
问题描述(包含复现issue方式):

如题。app中不显示功率和开机时间。我自己写的一个简易的mqtt client demo显示，固件会定时发出插座信息的消息，但是不再像之前版本每隔几秒发出功率和开机时间的信息。

通过手动发布这两个字段的查询命令，可以正确返回字段。

固件为刚刚从app设置中升级

![Screenshot_2019-10-08-22-47-26-080_com zyc zcontrol](https://user-images.githubusercontent.com/32010059/66406071-a255e480-ea1d-11e9-9e35-e9338f368bbb.jpg)

**Comment by everything411** [comment]
APP v0.12.3已解决

望更新通信协议Wiki页面

**Comment by a2633063** [comment]
通信协议Wiki页面已经更新
