### ISSUE TITLE
homeasistant接入代码有误？

### ISSUE THREAD

**Issue by hwj180** [a2633063/zTC1#50]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):V1.0.2

App版本(与app控制有关时必填):V0.12.4

Android版本(与app控制有关时必填):9

是否使用服务器(必填):
使用的是homeasistant自带的mqtt服务器
问题描述(包含复现issue方式):
现有两个tc1插排，一个使用的旧版V0.10.3固件，接入HA也是用的原来的代码，在HA里面能看到功率，也能对开关进行控制。
另一个插排刷的最新的V1.0.2版本固件，接入HA采用的你最新的代码，但是在HA里面无法获取功率和时间，点击改变开关状态没有效果，且过几秒又回到off态。

**Comment by a2633063** [comment]
请先确认手机app能够通过mqtt控制设备

**Comment by hwj180** [comment]
手机APP在局域网里面是可以的，但是不在家里就不行了。老固件那个在外网也还是可以正常显示和控制的。

**Comment by hwj180** [comment]
旧固件那个也是用的这个HA自带的MQTT服务器啊。旧固件的插排能控制，我就认为mqtt服务器没有问题。

**Comment by a2633063** [comment]
不是你服务器有问题  是排插和服务器通信有问题

**Comment by a2633063** [comment]
确认mqtt服务器信息有同步给排插

**Comment by a2633063** [comment]
看文档

**Comment by hwj180** [comment]
我在家里用APP能控制这个新固件的插排，是不是就认为我MQTT通信没问题。APP控制插排需要经过我的MQTT服务器吗？

**Comment by a2633063** [comment]
不是 如果app勾局域网通信连上了 那么就算app连接了mqtt服务器也会使用局域网udp通信 这时无法验证排插是否连上mqtt

**Comment by a2633063** [comment]
说明你排插和mqtt服务器通信异常,和hass无关

**Comment by hwj180** [comment]
同一个局域网下，一个新固件插排，一个旧固件插排，旧固件插排能与MQTT服务器通信，新固件不能，这个真不知道如何分析了。

**Comment by a2633063** [comment]
确认mqtt服务器信息有同步给排插

**Comment by hwj180** [comment]
好的，我再试试，谢谢大佬讲解。
