### ISSUE TITLE
MQTT服务器地址长度限制

### ISSUE THREAD

**Issue by kukugtu** [a2633063/zTC1#52]
固件版本(必填):所有

App版本(与app控制有关时必填):无关

Android版本(与app控制有关时必填):无关

是否使用服务器(必填):是

问题描述(包含复现issue方式):过长都mqtt地址配置失败。看起来是接收数据的时候接收不完整。
至少百度云都mqtt地址超长了，域名+端口号长度37字符

**Comment by a2633063** [comment]
域名长度最长为31个字节,不能超过31,后续看情况更新固件修复

**Comment by a2633063** [comment]
> 修改mqtt服务器长度最长47个字符

版本v1.1.0修复此问题.请更新到最新版本.
