### ISSUE TITLE
ota升级之之后原配网信息消失

### ISSUE THREAD

**Issue by 925934787** [a2633063/zTC1#53]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):0.10.4 升级1.0.2

App版本(与app控制有关时必填):最新

Android版本(与app控制有关时必填):10

是否使用服务器(必填):是

问题描述(包含复现issue方式):从旧版本升级到最近1.0.2，原来的中文名的配网信息消失，直接处于配网状态，但是还是使用原来中文名的网络配网，页面返回成功，但是插座几个电源口开启之后又断开，配网并没有成功

**Comment by a2633063** [comment]
不建议使用中文ssid,由于中文编码的不同,会导致中文的ssid在不同设备上编码不同从而导致设备无法连接.
建议对于IoT设备,使用英文ssid
