### ISSUE TITLE
升了1.0.2之后，无法重新获取数据激活状态，可以怎么搞？

### ISSUE THREAD

**Issue by smart-z** [a2633063/zTC1#54]
点了1.0.2升级，完了提示升级成功了。
但是此时app上无法重新获取激活状态，只有三个插口是开的，3个是关的。点激活状态也会提醒“未获取到当前设备激活信息”的alert。
那如何获取激活状态。咋整？

**Comment by kendwk** [comment]
今天刚升级，也有同样的问题，盒子正面的按钮也完全失效。

**Comment by smart-z** [comment]
不清楚什么情况，某天重新开始折腾，结果可以连上了，然后才做了重新激活。
但是，可能某次升级还是什么出了问题，导致其中一个插排的功率检测不到。
