### ISSUE TITLE
建议文档中添加提示 当版本大于1.0时 关闭 使用旧版本通信 。

### ISSUE THREAD

**Issue by fengsuxing** [a2633063/zTC1#55]
这个选项默认是勾选的。由于本人没加群。弄了好久才发现是这个选项导致MQTT连接时，APP操控异常。文档并未提及这个选项不兼容新版本

**Comment by a2633063** [comment]
![image](https://user-images.githubusercontent.com/19439881/68655241-a4561a80-056a-11ea-9947-31462f24f07d.png)


please close the issue

**Comment by fengsuxing** [comment]
默认勾选大部分人都会认为兼容老固件吧!
