### ISSUE TITLE
配置MQTT服务后，如果MQTT服务器短暂时间失联，则会永久不能连MQTT服务

### ISSUE THREAD

**Issue by ewayboy** [a2633063/zTC1#57]
固件版本(必填):0.10.4 升级1.0.2

App版本(与app控制有关时必填):最新

Android版本(与app控制有关时必填):10

是否使用服务器(必填):是

问题描述(包含复现issue方式):配置MQTT服务后，如果MQTT服务器短暂时间失联（网络故障或者是mqtt服务重启），则会永久不能连MQTT服务，需要使用android app再次配置刷新使用mqtt服务才能连上。

**Comment by a2633063** [comment]
重新启动排插也不行吗

**Comment by ewayboy** [comment]
排插不能重启，因为排插还有其他设备不能断电。使用mqtt的原因是远程控制。目前是mqtt服务失联后就必须在局域网内使用app刷新一次使用mqtt服务才能继续连接。

**Comment by a2633063** [comment]
麻烦确认重启是否会重新连接.
连接后如果可以连接 此issue和https://github.com/a2633063/zTC1/issues/49问题相同,请关闭此问题  在那个问题下回复 thanks
