### ISSUE TITLE
PDD阿木商城是作者么

### ISSUE THREAD

**Issue by techistoner** [a2633063/zTC1#58]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):

App版本(与app控制有关时必填):

Android版本(与app控制有关时必填):

是否使用服务器(必填):

问题描述(包含复现issue方式):

**Comment by a2633063** [comment]
不是我   我有授权给他们卖刷好的tc1 a1版本
他们的远程控制版也是我为他们定制开发的
