### ISSUE TITLE
请问一下usb接口可以单独控制吗

### ISSUE THREAD

**Issue by ck003** [a2633063/zTC1#62]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填): v1.0.2

App版本(与app控制有关时必填): v0.13.3

Android版本(与app控制有关时必填): 7.0

是否使用服务器(必填): 否

问题描述(包含复现issue方式): 请问一下usb接口可以单独控制吗？

**Comment by a2633063** [comment]
不可以  硬件限制
