### ISSUE TITLE
路由器连接在插座上，通电以后插口没有电，没有网络无法控制

### ISSUE THREAD

**Issue by xhlgood0525** [a2633063/zTC1#65]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):v1.0.2

App版本(与app控制有关时必填):v0.13.3

Android版本(与app控制有关时必填):9.0

是否使用服务器(必填):否

问题描述(包含复现issue方式):路由器电源大插在下面一排，插座通电下面一排没有电，无法联网，导致无法控制开关，是否可以通电默认下面插口有电。

**Comment by a2633063** [comment]
激活 另外app有新版 请更新app
