### ISSUE TITLE
TC1不上报插孔状态数据

### ISSUE THREAD

**Issue by fantasyjqc** [a2633063/zTC1#66]
固件版本(必填):v1.0.2

是否使用服务器(必填):自己搭建的MQTT服务器

问题描述(包含复现issue方式):

发现使用一段时间之后TC1不会再上报插孔的状态，我这边的情况是通过MQTT接入到NR中，例如插孔是全部打开的，因为没有开启Retain，重启NR之后，Homekit中插孔会暂时变成全关状态，等待发送一次状态数据之后变成全开。

但是使用一段时间之后，如果一直没有改变插孔状态，那么TC1不会再上报状态，如果重启NR，Homekit中的插孔永远都是关闭，此时在Homekit中控制插孔是正常的，可以开关插孔，但是依然拿不到TC1插孔的状态。

多次尝试解决没能解决问题，然后找来了PC端的控制软件，在上面设备的插孔状态也是都关闭的，必须要点击一次同步MQTT服务器，才能正常显示，然后在上面任意开关一个插孔，Homekit就能恢复正常了，似乎这样TC1的状态上报就恢复了。但是正常使用一段时间之后依然会再次出现不上报状态的问题。

**Comment by a2633063** [comment]
当前最新版本v1.1.0中反馈已经增加了Retain.
v1.0.2已经增加了retain. 还是建议ota到最新版本.ota前请仔细阅读app中ota更新说明
