### ISSUE TITLE
希望增加小爱或者天猫精灵之类的智能音响

### ISSUE THREAD

**Issue by mmkkllpp** [a2633063/zTC1#68]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):
1.1.0
App版本(与app控制有关时必填):
1.4.3
Android版本(与app控制有关时必填):
9.0
是否使用服务器(必填):
mqtt
问题描述(包含复现issue方式):
首先要感谢大佬开发了TC1的固件，从而让TC1死而复生，个人对固件很满意，mqtt也使用正常，如果固件能支持智能音响那就完美了，不知道大佬有没有增加智能音箱控制的想法呢

**Comment by a2633063** [comment]
智能音响控制只和服务器有关.为了防止服务器异常或部分人介意接入个人的服务器.  本人不提供专用服务器使用.
如果需要智能音箱控制.请自己搭建hass或nr服务器来接入
