### ISSUE TITLE
中文ssid不支持

### ISSUE THREAD

**Issue by hlhk2017** [a2633063/zTC1#69]
固件版本: v1.1.0
问题描述(包含复现issue方式):最近做家里网络改动，准备全部换成中文ssid，但此固件在web配网时提示保存成功，但无法连接网络。
0.10.4版本是APP配网，不知道是不是可以连接中文ssid，在此咨询一下。
如果下一版固件能提供支持就好了。我会抽空尝试旧版固件。

**Comment by a2633063** [comment]
不支持中文ssid   也没有计划支持中文ssid
