### ISSUE TITLE
重大BUG ： 路由器外网故障（可能是DNS相关查询异常）导致tc1闪断

### ISSUE THREAD

**Issue by babylife** [a2633063/zTC1#7]
更新故障重现步骤：
测试步骤1 ：
1. 正确配置TC1 WIFI ，并确保手机可控。
2. 修改路由器DNS地址，比如配置192.168.3.3 此类不可达IP，注意LAN口的DNS和WAN的DNS可同步修改。我测试的时候顺便拔除了WAN的网线，注意，此路由器非PPPOE拨号路由器
3. 重启路由器。 
4. 观察TC1， 此时状态LED灯，跳闪并重复连接正常，LED常亮。
5. 等待约一分钟后，开始闪断，此后每50秒左右闪断。 
6 重启TC1电源，故障一样。 
7 恢复路由器DNS配置，问题没有解决
8 恢复路由器WAN口的外网链接，问题解决。 

进一步测试2:
只要拔出WAN口的网线，让路由器没有外网访问就可以重现问题，我的天啊，太可怕了。 

======================

猜测TC1需要查询DNS的记录，但是没有返回结果，就会导致故障
不方便抓取网络包查看其DNS查询的信息，最好有个LEDE的路由，方便查询DNS
====================
路由器偶然重启 dnsmaq服务没法启动，发现会导致tc1持续闪断。虽然是路由器故障 但是我的理解不应该导致tc1反复闪断。
手动修复路由器dnsmaq服务后tc1恢复正常
望大神检查下dns相关的代码逻辑

**Comment by a2633063** [comment]
未找到路由器下dns关闭的相关选项.
另外:由于路由器刷个人固件后,无法确认路由器的稳定及功能完全正常,所以请使用路由器的官方固件测试确认

**Comment by babylife** [comment]
理解 没有大碍

**Comment by babylife** [comment]
可以测试关注路由器重启后DNS服务器不可达或者为空的场景，我这边也配合测试

**Comment by babylife** [comment]
已更新确认是ntp查询，坐等群主更新最终结果

**Comment by d8c8** [comment]
求解决这个问题的方案啊 每天公司晚上断外网，刷刷第一天不知道有这个问题，我得台式机还开着，，，硬盘彻底挂了。。。。。。

**Comment by darktitty** [comment]
真的很蛋疼 断的我怕啦 不知道我想变回普通插座还有可能吗？

**Comment by a2633063** [comment]
此问题已经解决  但是因为被不法商用的问题暂时不会放出  会尽快解决后才会考虑放出解决此问题的固件 抱歉

**Comment by babylife** [comment]
OK
