### ISSUE TITLE
Z智能控制微信公众号无法使用了吗？怎么获取激活码呢？

### ISSUE THREAD

**Issue by yunsean** [a2633063/zTC1#77]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):

App版本(与app控制有关时必填):

Android版本(与app控制有关时必填):

是否使用服务器(必填):

问题描述(包含复现issue方式):

**Comment by a2633063** [comment]
确认了下  公众号正常
可以发送help确认发送关键词
