### ISSUE TITLE
如何通过MQTT控制童锁与logo灯 开关？

### ISSUE THREAD

**Issue by aihhkc** [a2633063/zTC1#78]
> 请先搜索确认没有重复后再提交issue,以下内容若未按照模板填写,不做任何回复,3天后若未更新直接关闭issue.

固件版本(必填):V1.2.1

App版本(与app控制有关时必填):

Android版本(与app控制有关时必填):

是否使用服务器(必填):是

问题描述(包含复现issue方式):

**Comment by a2633063** [comment]
wiki通信协议中有相关说明

**Comment by aihhkc** [comment]
查到了，谢谢，之前没认真看，
