### ISSUE TITLE
ZTC1掉激活状态

### ISSUE THREAD

**Issue by dbqty** [a2633063/zTC1#82]
固件版本(必填):1.2.1

App版本(与app控制有关时必填):v1.12.0

Android版本(与app控制有关时必填):

是否使用服务器(必填):MQTT

问题描述(包含复现issue方式):ZTC1配网完成激活后，再使用MQTT时，激活会变成未激活，重新激活后，再次点击MQTT云朵图标后，仍变成未激活，需要重新激活。

**Comment by dbqty** [comment]
使用PC客户端同步，仍然掉激活状态，另外，插口1 会变成 veraeBeph2vohm

**Comment by a2633063** [comment]
尝试设置多个插口名 设置几个定时 后同步mqtt服务器(不用激活)
重启后确认名称定时及mqtt服务器正常
若不正常可能是主控flash储存损坏

**Comment by a2633063** [comment]
> 尝试设置多个插口名 设置几个定时 后同步mqtt服务器(不用激活)
> 重启后确认名称定时及mqtt服务器正常
> 若不正常可能是主控flash储存损坏

用以上方法但是不同步mqtt服务器再试
如果没有问题 尝试缩短mqtt域名/用户名密码再试

**Comment by dbqty** [comment]
密码过长导致，麻烦大佬了。
