### ISSUE TITLE
希望修改重新配网的操作模式

### ISSUE THREAD

**Issue by babylife** [a2633063/zTC1#9]
断电+按钮为重置方法
长按10秒为重新配网
希望老大考虑下

**Comment by babylife** [comment]
目前APP可以实现重启功能，变相解决配网问题， 老大如不想做此功能可以close这个单子

**Comment by a2633063** [comment]
暂时不关,后续不确定是否会修改配网方式

**Comment by Caffreyfans** [comment]
可以加中断，然后让固件恢复出厂设置

**Comment by a2633063** [comment]
已经确认下个版本会修改配网方式为web配网

**Comment by a2633063** [comment]
更新v1.0.0固件版本,已经修改配网方式为web配网
